# Generated by Django 2.1.3 on 2019-04-09 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190328_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='user',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
    ]
