# Generated by Django 2.1.3 on 2019-03-04 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Espera', 'Espera'), ('Revisado', 'Revisado'), ('Sin revisar', 'Sin revisar'), ('Exitoso', 'Exitoso'), ('Fallido', 'Fallido')], default='Espera', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('curp', models.CharField(blank=True, max_length=50, null=True)),
                ('ine', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('imagen', models.ImageField(upload_to='Publications')),
                ('latitud', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_creacion', models.DateField(null=True, verbose_name='Fecha en que la foto fue tomada (ej. 03/03/2019)')),
                ('hora_creacion', models.TimeField(null=True, verbose_name='Hora en que la foto fue tomada (ej. 12:00)')),
                ('modelo_cel', models.CharField(blank=True, max_length=100, null=True, verbose_name='modelo del telefono')),
                ('status', models.CharField(blank=True, choices=[('Espera', 'Espera'), ('Revisado', 'Revisado'), ('Sin revisar', 'Sin revisar'), ('Exitoso', 'Exitoso'), ('Fallido', 'Fallido')], default='Espera', max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_envio', 'order'],
            },
        ),
        migrations.AddField(
            model_name='estatus',
            name='id_pro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile'),
        ),
        migrations.AddField(
            model_name='estatus',
            name='id_pub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Publication'),
        ),
        migrations.AddField(
            model_name='estatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
