# Generated by Django 2.1.3 on 2019-03-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190308_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='status',
        ),
    ]
