# Generated by Django 2.1.3 on 2019-03-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_publication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatus',
            name='id_pro',
        ),
        migrations.RemoveField(
            model_name='estatus',
            name='id_pub',
        ),
    ]
