# Generated by Django 2.1.3 on 2019-03-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_publication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatus',
            name='user',
        ),
        migrations.AlterField(
            model_name='estatus',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
