# Generated by Django 2.1.3 on 2019-03-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190308_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Estatus'),
        ),
    ]
