# Generated by Django 2.1.3 on 2019-03-09 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20190309_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='estatus',
        ),
        migrations.AddField(
            model_name='estatus',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Publication'),
        ),
    ]
