# Generated by Django 2.1.3 on 2019-03-09 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20190309_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsPub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='estatus',
            name='publication',
        ),
        migrations.AddField(
            model_name='espub',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Estatus'),
        ),
        migrations.AddField(
            model_name='espub',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Publication'),
        ),
    ]
