# Generated by Django 2.1.3 on 2019-03-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20190309_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espub',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='espub',
            name='publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Estatus'),
        ),
        migrations.DeleteModel(
            name='EsPub',
        ),
    ]
