# Generated by Django 2.1.3 on 2019-03-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20190310_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='curp',
            new_name='titulo',
        ),
    ]
