# Generated by Django 2.1.3 on 2019-03-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20190321_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ine',
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_nac',
            field=models.DateField(null=True, verbose_name='fecha de nacimiento (ej. 03/03/2019)'),
        ),
    ]
