# Generated by Django 2.1.3 on 2019-03-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20190321_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='edu',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exp',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
