# Generated by Django 2.1.3 on 2019-03-23 00:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20190322_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created', 'order']},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='fecha_envio',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='hora_creacion',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='modelo_cel',
        ),
        migrations.AddField(
            model_name='publication',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='publication',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
