# Generated by Django 2.1.3 on 2019-03-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20190327_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Estatus'),
        ),
    ]
