# Generated by Django 2.1.3 on 2019-03-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_publication_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Publications'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Estatus', verbose_name='Agregar una catgoria'),
        ),
    ]
