# Generated by Django 2.1.3 on 2019-07-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_auto_20190328_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='titulo',
            new_name='enfoque_social',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='img_edu',
            new_name='img_miembros',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='img_hab',
            new_name='img_objetivos',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='img_exp',
            new_name='img_proyectos',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='edu',
            new_name='miembros',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='apellido_m',
            new_name='nombre_director',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='apellido_p',
            new_name='nombre_secretario',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='exp',
            new_name='objetivos',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='hab',
            new_name='proyectos',
        ),
        migrations.AlterField(
            model_name='profile',
            name='fecha_nac',
            field=models.DateField(null=True, verbose_name='fecha de creación de la organizacion (ej. 03/03/2019)'),
        ),
    ]
