# Generated by Django 2.1.3 on 2019-07-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20190713_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
