# Generated by Django 2.1.3 on 2019-07-28 18:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_profile_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='actividades',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Actividades'),
        ),
        migrations.AddField(
            model_name='publication',
            name='fecha',
            field=models.DateField(null=True, verbose_name='fecha de proyecto (ej. 03/03/2019)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='logistica',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Logistica'),
        ),
        migrations.AddField(
            model_name='publication',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='publication',
            name='overview',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='publication',
            name='requisitos',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Publications', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
    ]
