# Generated by Django 2.1.3 on 2019-07-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_publication_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='maps',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='maps'),
        ),
    ]
